FROM openjdk:slim
COPY --from=python:3.9 / /

WORKDIR /service

COPY requirements.txt /service/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /service/requirements.txt

RUN apt-get update

RUN apt-get install -y libsndfile1-dev

RUN python3 -m nltk.downloader stopwords

EXPOSE 80

ADD . /src

WORKDIR /src

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]